- name: PWSS
  image: PWSS.png
  text: Password Self Serive um dein Password selber zuückzusetzen
  link: https://pwss

- name: Regleungsportal
  image: regelungsportal.png
  text: Im Regleungsportal stehen Reglen uns vieles mehr 
  link: https://regelungsportal.vw.vwg

- name: GroupWiki
  image: groupwiki.png
  text: Das konzernweile Wiki
  link: https://groupwiki.vw.vwg


- name: GroupConnect
  image: groupwiki.png
  text: Das konzernweile Wiki
  link: https://groupwiki.vw.vwg


- name: GroupLearn
  image: grouplearn.png
  text: Lernportal
  link: https://groupwiki.vw.vwg